### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by Skips1** [kriptodostu/Github-Basarimlar#161]
Bu Issues Soru/Bilgilendirme/Konuşma yerimi ?

**Comment by kriptodostu** [comment]
Belirli bi problemi tartışma yeri galiba hiç kullanmadım

**Comment by Skips1** [comment]
Pul requ yu 2x yapbilir miyim senin başarımlarda 10 tane kaldı sanırım senin için bir mahsuru var mı?

**Comment by kriptodostu** [comment]
> Pul requ yu 2x yapbilir miyim senin başarımlarda 10 tane kaldı sanırım senin için bir mahsuru var mı?

yapabilirsin hocam ama manuel onaylıyorum yavaş olur

**Comment by kriptodostu** [comment]
> Pul requ yu 2x yapbilir miyim senin başarımlarda 10 tane kaldı sanırım senin için bir mahsuru var mı?

Otomatiğe aldım dene bakayım olmus mu

**Comment by Skips1** [comment]
Tamamdır

**Comment by Skips1** [comment]
Buda b

**Comment by kriptodostu** [comment]
Yok olmadı manuel onaylıyorum

**Comment by kriptodostu** [comment]
> Sana da zahmet veriyoruz hakkını helal et ##

Estf.

**Comment by Skips1** [comment]
![image](https://user-images.githubusercontent.com/98268472/207638675-260cc453-fcef-408c-a27e-ee7f8b03e59e.png)


Alev aldı buralar .d

**Comment by kriptodostu** [comment]
> ![image](https://user-images.githubusercontent.com/98268472/207638675-260cc453-fcef-408c-a27e-ee7f8b03e59e.png)
> 
> Alev aldı buralar .d

1 2 tane daha göndersene bişi denicem

**Comment by Skips1** [comment]
Hemen atıyorum

**Comment by kriptodostu** [comment]
> Hemen atıyorum

Githubda bi kaç şey daha öğrendim rozet bahanesine iyi oldu :D
